module Pokemon.Item where

data Item
    = MasterBall
    | UltraBall
    | GreatBall
    | PokeBall
    | TownMap
    | Bicycle
    | SafariBall
    | MoonStone
    | Antidote
    | BurnHeal
    | IceHeal
    | Awakening
    | ParlyzHeal
    | FullRestore
    | MaxPotion
    | HyperPotion
    | Potion
    | EscapeRope
    | Repel
    | OldAmber
    | FireStone
    | ThunderStone
    | WaterStone
    | HPUp
    | Protein
    | Iron
    | Carbos
    | Calcium
    | RareCandy
    | DomeFossil
    | HelixFossil
    | SecretKey
    | BikeVoucher
    | XAccuracy
    | LeafStone
    | CardKey
    | Nugget
    | PokeDoll
    | FullHeal
    | Revive
    | MaxRevive
    | GuardSpec
    | SuperRepel
    | MaxRepel
    | DireHit
    | FreshWater
    | SodaPop
    | Lemonade
    | SSTicket
    | GoldTeeth
    | XAttack
    | XDefend
    | XSpeed
    | XSpecial
    | CoinCase
    | OaksParcel
    | Itemfinder
    | SilphScope
    | Pokeflute
    | LiftKey
    | ExpAll
    | OldRod
    | GoodRod
    | SuperRod
    | PPUp
    | Ether
    | MaxEther
    | Elixer
    | MaxElixer
    deriving (Eq, Show, Ord)
